### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-hk2#389]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by arjantijms** [comment]
Project CI environment has been requested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538693

**Comment by ankathur** [comment]
Created build job https://jenkins.eclipse.org/glassfish/view/hk2/job/hk2-build-job/.
