### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-hk2#390]
This task is for creating a project release CI/CD pipeline. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by ankathur** [comment]
Release Job https://jenkins.eclipse.org/glassfish/job/hk2-release-job/ created and artifacts are released to OSSRH.
