### ISSUE TITLE
HK2-Configuration ServiceLocator.shutdown throws ConcurrentModificationException

### ISSUE THREAD

**Issue by exas** [eclipse-ee4j/glassfish-hk2#412]
I am using at my project the HK2-Configuration feature `(@ConfiguredBy` and `@Configured` annotations) as provided in the HK2 **webserver-configuration-example** for multiple Services.

Following odd behaviour i noticed:
- If i use the Configurations with one Service a ServiceLocator `shutdown()` call will work perfectly fine.
- If i use the Configurations with more than one Service a ServiceLocator `shutdown()` at the end of my program results into:
`java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at org.glassfish.hk2.configuration.internal.ConfiguredByContext.shutdown(ConfiguredByContext.java:165)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.shutdown(ServiceLocatorImpl.java:926)`

Therefore at the moment i am not able to make a proper "shutdown" and cleanup at the end of my project. My workaround for now is that i manually shutdown the crucial services instead of expecting that preDestroy is being called.

**To reproduce:**
reproduce the error by slightly adapting the Test of **webserver-configuration-example**. 
Just add `    @After
    public void after() {
    	locator.shutdown();
    }` to the test and it should result in the exact described ConcurrentModificationException as described.

**Comment by exas** [comment]
Is this an issue with the Configuration annotation?

**Comment by svendiedrichsen** [comment]
@exas Would you mind confirming the fix?
