### ISSUE TITLE
maven-metadata is missing all versions besides 2.5.0

### ISSUE THREAD

**Issue by balta3** [eclipse-ee4j/glassfish-hk2#439]
Since today in https://repo1.maven.org/maven2/org/glassfish/hk2/hk2-api/maven-metadata.xml there is just the version 2.5.0 listed, so that for example range version dependencies are not working anymore.

**Comment by romain-grecourt** [comment]
I'd say you should file an issue with Sonatype, it may be related to the change of nexus used to publish the artifacts (used to be maven.java.net, now oss.sonatype.org).

**Comment by balta3** [comment]
When did Sonatype change anything? It was working until yesterday, where you created the release of 2.5.0

Where can I fill an issue at Sonatype?

**Comment by balta3** [comment]
I have no account at sonatype.org, so I cannot file an issue :(

Sadly since today we have the same problem with jersey-common. At the moment our workaround is to put the _missing_ versions in our internal repository, but this is no real solution.

**Comment by pzygielo** [comment]
> I have no account at sonatype.org, so I cannot file an issue :(

You can [sign up](https://issues.sonatype.org/secure/Signup!default.jspa) for one.

But - if it shall be the case for all components of EE4J that kept maven G:A coordinates - I also think it shall be handled by Eclipse.

**Comment by Cousjava** [comment]
This has now been fixed by Sonatype
