### ISSUE TITLE
Support for java.util.Optional

### ISSUE THREAD

**Issue by buko** [eclipse-ee4j/glassfish-hk2#457]
hk2 hould support injection of fields of type java.util.Optional.

See #234 for a similar feature request.

1. If a field is of type java.util.Optional HK2 should interpret this as optional injection. It's the same as if it was injecting a raw type annotated with @Optional.

2. As java.util.Optional is everywhere now (including Android) it seemsOp there should be no objection to including it in hk2's core API.

3. It is possible (though unlikely) a user might want to inject an Optional value. We might implement this as a JustInTimeInjectionProvider to detect an attempt to inject a java.util.Optional and trigger our injection logic.

4. Optional<javax.inject.Provider<T>> should also be supported. In this case we would like to allow for lazy creation of an Optional service.

5. HK2 should support Optional injection and allow the Factory.provide() method returns null. That is, if the Factory.provide() returns null and it is an Optional injection then this should not be declared an error. The Optional injection should still be considered satisfied. This is very useful, for example, because Remote Services are commonly not present when no internet connection is available. We can return an 'Offline Implementation' of the Remote Service but this is a bit meaningless. If the Remote Service is unavailable it'd be simpler to model that using Optional. Another common case is to have Services that are only present if some configuration value is et.  

This is a low-priority feature (it's easy enough to implement) but implementing it in the core does save plenty of people from implementing the same functionality over and over over...

**Comment by jwells131313** [comment]
I agree that hk2 should have this feature

**Comment by Cousjava** [comment]
Implemented by #466
