### ISSUE TITLE
ServiceLocator Exceptions should include the Locator Name

### ISSUE THREAD

**Issue by buko** [eclipse-ee4j/glassfish-hk2#491]
Exceptions like `UnsatisfiedDependencyException` and `DuplicateServiceException` (perhaps all the descendants of HK2RuntimeException) do not include any information about the name of the ServiceLocator that generated the exception. In a relatively deep hierarchy of SLs this can make it difficult to track down exactly where/how the exception is happening. It'd be very useful to include the Locator name in the error message.

**Comment by smillidge** [comment]
Do you think you could make a PR?

**Comment by buko** [comment]
It's problematic for me because I'm told I shouldn't sign the ECA. Will continue to peek into this.
