### ISSUE TITLE
Jakartification of HK2

### ISSUE THREAD

**Issue by jbescos** [eclipse-ee4j/glassfish-hk2#504]
During the jakartification of the JAXRS TCK I realized that we need to update some jakarta dependencies updates in HK2 (currently they use javax instead of jakarta). This is because JAXRS TCK tests depends on Jersey and Jersey depends on HK2.

If nobody else is working on this, I can do it if you want.

**Comment by smillidge** [comment]
There is a PR here https://github.com/eclipse-ee4j/glassfish-hk2/pull/501

**Comment by jbescos** [comment]
Thanks @smillidge I close this.

**Comment by smillidge** [comment]
Thanks for the offer #501 is stuck on what to do about 3rd party test dependencies
