### ISSUE TITLE
HK2 needs to make an M2 release

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/glassfish-hk2#513]
GlassFish needs a M2 release in staging incorporating https://github.com/eclipse-ee4j/glassfish-hk2/pull/512 for the June release

**Comment by mkarg** [comment]
This issue just got more urgent as the Jersey team already pushed their M6 into Maven Central which depends on HK2-Locator 3.0.0-M2, see https://github.com/eclipse-ee4j/jersey/issues/4521. If there is no real showstopper, I do plea for publishing M2 immediately.

**Comment by smillidge** [comment]
So you need it in maven central? I will try and push the button some time today.

**Comment by smillidge** [comment]
This is now in the Releases repo on jakarta.oss so should replicate across to central.

**Comment by mkarg** [comment]
Thank you so much! I confirm it is found in Maven Central now. So everybody can simply use latest Jersey 3.0.0-M6 now! :rocket:
