### ISSUE TITLE
Push HK2 3.0.0-RC1 to maven central

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/glassfish-hk2#531]
In maven central, currently, the 3.0.0-M2 is available. Jersey 3.0.0 depends on  HK2 3.0.0-RC1 which is in staging. Is it possible to push the RC1 to cetral?

**Comment by smillidge** [comment]
Should be on its way. I released it in jakarta.oss.sonatype.org

**Comment by jansupol** [comment]
Yes, I can see it in maven central. Thank you
