### ISSUE TITLE
Wrong plugin versions in pom.xml

### ISSUE THREAD

**Issue by hussainnm** [eclipse-ee4j/glassfish-hk2#537]
As part of version update in b8ab38d1320e2ecc3ce7304d0e6d59839ee22f21 the following plugins have been accidentally updated to 3.0.1-SNAPSHOT

https://github.com/eclipse-ee4j/glassfish-hk2/blob/b8ab38d1320e2ecc3ce7304d0e6d59839ee22f21/pom.xml#L394-L398

https://github.com/eclipse-ee4j/glassfish-hk2/blob/b8ab38d1320e2ecc3ce7304d0e6d59839ee22f21/pom.xml#L505-L509

I suspect these got updated by the release jenkins job. Ideally the release-plugin will only update the pom version and will not touch the plugins or dependencies.

I will create a PR with fix for the above plugins but it is also important to identify and fix the cause of this issue.

**Comment by Cousjava** [comment]
Fixed in #538
