### ISSUE TITLE
Please push tag that was used to produce 3.0.2

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish-hk2#553]
https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/hk2/hk2-bom/3.0.2/

**Comment by smillidge** [comment]
Weird @arjantijms ran the job https://ci.eclipse.org/glassfish/view/all/job/all-projects_1_build-and-stage/61/console and the log files says it created a tag `git tag 3.0.2 -m 'Release 3.0.2'` and created a branch ` git commit -m 'Prepare next development cycle for 3.0.3'
[3.0.2-BRANCH efd8f1e] Prepare next development cycle for 3.0.3`

**Comment by smillidge** [comment]
Ah push to github was not selected on the job. @arjantijms any idea why not?

**Comment by arjantijms** [comment]
Hi,

On Thursday, May 27, 2021, Steve Millidge ***@***.***> wrote:

> Ah push to github was not selected on the job. @arjantijms
> <https://github.com/arjantijms> any idea why not?
>
Yes, there was an issue at the time with the bot’s access to GitHub. It
would fail the job.

The exact git ref that is was used when the job executed is in the job
history though.

**Comment by pzygielo** [comment]
> The exact git ref that is was used when the job executed is in the job
history though.

I can only see
```
+ git checkout -b 3.0.2-BRANCH
Switched to a new branch '3.0.2-BRANCH'
```

It doesn't say where it was branched from.

And since
```
[3.0.2-BRANCH efd8f1e] Prepare next development cycle for 3.0.3
```
wasn't pushed to github I'm pretty sure it's gone as agent was destroyed.

I guess a317aaf was used to start release with.

**Comment by arjantijms** [comment]
> It doesn't say where it was branched from.

You're right. I'm not super Jenkins expert, so I've to investigate why the rev is not listed. It is, for instance, listed here:

https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_1-build-and-stage/125/

<img width="710" alt="Screenshot 2021-05-27 at 17 17 14" src="https://user-images.githubusercontent.com/3037006/119852219-6384e300-bf0f-11eb-954b-67cd456de110.png">

**Comment by pzygielo** [comment]
Closing, as I assume it's undoable.
