### ISSUE TITLE
Memory leak in PerContextThreadWrapper

### ISSUE THREAD

**Issue by plesingr-aeb** [eclipse-ee4j/glassfish-hk2#949]
There is problem with the `registerStopEvent` in `PerThreadContext$PerContextThreadWrapper`. The registration keeps a reference to the wrapper in both the monitored object (`this`) and the cleanup action (`this.instances`). That causes an eternal reference to the wrapper, together with all the cached values.

It was probably originally intended to monitor the `PerThreadContext` object. But the whole registration is **not necessary at all**, because when the wrapper gets collectable (as it happens via `PerThreadContext.shutdown()`), the contained `instances` map is going to be released, too.

The whole problem is reproducible with Jersey clients and XML payload:
[JerseyMemoryTest.txt](https://github.com/eclipse-ee4j/glassfish-hk2/files/13739055/JerseyMemoryTest.txt)

**Comment by avpinchuk** [comment]
@plesingr-aeb, thank you for detailed explanation
